=== RamiroGarciaAr/MusicBrainzAPI/artist_data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="artist_data" type="resultT"/>
 <xsd:complexType name="resultT">
   <xsd:choice>
        <xsd:element name="artist" type="artistT"/>
    	<xsd:element name="error" type="xsd:string" minOccurs="1" maxOccurs="unbounded" />
   </xsd:choice>
 </xsd:complexType>

 <xsd:complexType name="artistT">
    <xsd:sequence>
        <xsd:element name="name" type="xsd:string"/>
        <xsd:element name="disambiguation" type="xsd:string"/>
        <xsd:element name="type" type="xsd:string"/>
        <xsd:element name="area" type="areaT"/>
        <xsd:element name="life-span" type="lifespanT"/>
        <xsd:element name="recordings" type="recordingsT"/>
    </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="recordingsT">
   <xsd:sequence>
 		<xsd:element name="recording" minOccurs="0" maxOccurs="unbounded" type="recordingT"/>
 	</xsd:sequence>
</xsd:complexType>

 <xsd:complexType name="recordingT">
   <xsd:sequence>
 		<xsd:element name="title" type="xsd:string"/>
        <xsd:element name="length" type="xsd:string"/>
        <xsd:element name="first-release-date" minOccurs="0" type="xsd:string"/>
        <xsd:element name="release" minOccurs="0" maxOccurs="unbounded" type="releaseT"/>
 	</xsd:sequence>
</xsd:complexType>

 <xsd:complexType name="areaT">
     <xsd:sequence>
         <xsd:element name="name" type="xsd:string"/>
         <xsd:element name="origin" type="xsd:string"/>
     </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="lifespanT">
     <xsd:sequence>
         <xsd:element name="begin" type="xsd:string"/>
         <xsd:element name="end" type="xsd:string"/>
         <xsd:element name="ended" type="xsd:boolean"/>
     </xsd:sequence>
 </xsd:complexType>

 <xsd:complexType name="releaseT">
     <xsd:sequence>
         <xsd:element name="title" type="xsd:string"/>
         <xsd:element name="date" type="xsd:string"/>
         <xsd:element name="country" minOccurs="0" type="xsd:string"/>
         <xsd:element name="type" type="xsd:string"/>
         <xsd:element name="subtype" minOccurs="0" type="xsd:string"/>
         <xsd:element name="track-number" minOccurs="0" type="xsd:string" />
     </xsd:sequence>
 </xsd:complexType>

</xsd:schema>

=== RamiroGarciaAr/MusicBrainzAPI/artist_data.xml
<?xml version="1.0" encoding="UTF-8"?><artist_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="artist_data.xsd"><artist><name>Pink Floyd</name><disambiguation/><type>Group</type><area><name>England</name><origin>London</origin></area><life-span><begin>1965</begin><end>2014</end><ended>true</ended></life-span><recordings><recording><title>Run Like Hell</title><length>237813</length><first-release-date>2001</first-release-date></recording><recording><title>Shine On You Crazy Diamond</title><length>800906</length><first-release-date/></recording><recording><title>Learning to Fly</title><length>334200</length><first-release-date/></recording><recording><title>Take It Back</title><length>346786</length><first-release-date/></recording><recording><title>Sorrow</title><length>666760</length><first-release-date/></recording><recording><title>Keep Talking</title><length>457053</length><first-release-date/></recording><recording><title>Another Brick in the Wall</title><length>413000</length><first-release-date>1994</first-release-date></recording><recording><title>One of These Days</title><length>316000</length><first-release-date>1991</first-release-date></recording><recording><title>Set the Controls for the Heart of the Sun</title><length>590000</length><first-release-date>1991</first-release-date></recording><recording><title>Dark Side of the Moon</title><length>2831000</length><first-release-date>1991</first-release-date></recording><recording><title>Breathe</title><length>174200</length><first-release-date/></recording><recording><title>On the Run</title><length>430240</length><first-release-date/></recording><recording><title>Time / Breathe (reprise)</title><length>745333</length><first-release-date/></recording><recording><title>Money</title><length>421360</length><first-release-date/></recording><recording><title>Us and Them</title><length>279506</length><first-release-date/></recording><recording><title>Any Colour You Like</title><length>121093</length><first-release-date/></recording><recording><title>Brain Damage</title><length>187840</length><first-release-date/></recording><recording><title>Eclipse</title><length>118000</length><first-release-date/></recording><recording><title>Milky Way</title><length>187000</length><first-release-date>1991</first-release-date></recording><recording><title>Let There Be More Light</title><length>212333</length><first-release-date>1991</first-release-date></recording><recording><title>The Narrow Way</title><length>259666</length><first-release-date>1989</first-release-date></recording><recording><title>Green Is the Colour</title><length>365000</length><first-release-date>1989</first-release-date></recording><recording><title>Astronomy Domine</title><length>538040</length><first-release-date>1991</first-release-date></recording><recording><title>Interstellar Overdrive</title><length>798933</length><first-release-date>1991</first-release-date></recording><recording><title>Cymbaline</title><length>514400</length><first-release-date>1991</first-release-date></recording></recordings></artist></artist_data>
